spring:
  ai:
    openai:
      api-key: test-key
      chat:
        options:
          model: gpt-4o-mini
    ollama:
      enabled: false

  autoconfigure:
    exclude:
      - org.springframework.ai.ollama.autoconfigure.OllamaAutoConfiguration
